# Generated by Django 2.0.3 on 2018-06-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
