# Generated by Django 2.0.3 on 2018-08-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIHome', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
